### ISSUE TITLE
Suggestion: Longer time window for pressing the Speak Aloud key

### ISSUE THREAD

**Issue by tflo** [Nodd/Verbose#41]
I have only started using your very nice add-on, and I often have issues with the very short duration of the time window where I can hit my Speak Aloud key.

For obvious reasons, all my easy-to-reach keys are mapped to spells and other important things. So I have to map the Verbose Speak Aloud function to some key on the other end of the keyboard plus modifier, which means it takes some time until I find and press the key combo.

A time window of at least 6 or 8 seconds would be highly appreciated. (Currently it seems to be something like 2 or 3 seconds?)
Ideally, the time window would be adjustable in the settings.

As a second suggestion, also an adjustable delay between event/spell and activation would be handy. (Maybe two different adjustable delay settings, so we could have one – shorter or zero – for spells, and another one – usually longer – for events like end of combat or merchant, etc.)

Thanks for considering.

And many thanks for developing this very interesting add-on!

– Tom

**Comment by tflo** [comment]
No reply after 1 week?! Is this add-on dead?

Would highly appreciate a reply, even if negative (= you don’t agree with my suggestion). Or any reaction at all.

TIA
– Tom

**Comment by Nodd** [comment]
Sorry again for the delay, I wasn't on github the last few weeks.

The delay is indeed quite short, I wanted to keep a short time frame between a trigger and the speech. If you cast a fireball and yell "burn !" while casting a frostbolt it can get weird. But I agree with you that it's too short right now so I'll set it higher.
I'd like to avoid adding yet another config option (even if it's quite easy to do) so for now it'll stay fixed. If it's really a problem in the future I'll make it configurable.

As for the delay I thought about it but didn't have time to implement it. In my mind it could be an option like in #27 like [delay=2], so that it would be configurable by message. Would that fit your needs ? Of course that means that I have to implement #27 first…

**Comment by tflo** [comment]
Thanks for your reply, highly appreciated.

> I wanted to keep a short time frame between a trigger and the speech. If you cast a fireball and yell "burn !" while casting a frostbolt it can get weird.

Yes, for spells this is true. I use Verbose mainly for NPC interaction or Leaving Combat events, etc., where a longer time window absolutely wouldn’t hurt. (Until now I don’t use it for spells at all (except Fishing), but this might change.)

I also have found an unoccupied key mapping a bit closer to my home row (M), so now I reach the key in time in 80% of the cases, lol. I’m a bit slow, I know ;) I even consider mapping it to one of the two top buttons of my Logitech G604 mouse…

For the delay suggestion: 

This was sort of an afterthought, but an optional delay of 2s or 1s doesn’t sound bad at all. I imagine this would be quite ideal for NPC interactions or Leaving Combat.

But don’t spend your time on this if you have more urgent stuff to do; I can also live without delay, a tiny bit more time to press the key is the more important thing.

Thanks again for this great add-on!

– Tom

**Comment by Nodd** [comment]
> I also have found an unoccupied key mapping a bit closer to my home row (M), so now I reach the key in time in 80% of the cases, lol. I’m a bit slow, I know ;) I even consider mapping it to one of the two top buttons of my Logitech G604 mouse…

You thought this was an RP addon ? No ! Its a game inside the game for checking your reflexes XD

I had pity on you and set the duration to 6s in the last version (which will become v1.0 if curseforge wakes up). FYI, before the delay was dependent on the number of characters in the message (with a minimum of 3s), which somehow looked like a good idea at the time.

**Comment by tflo** [comment]
> […] No ! Its a game inside the game for checking your reflexes XD

Yeah, I was almost perceiving it like that ;) 

> I had pity on you and set the duration to 6s in the last version

Oh, insanely great! I will report back how it plays.

> FYI, before the delay was dependent on the number of characters in the message (with a minimum of 3s)

Do you mean the delay or the reaction time window? In any case, doesn’t make much sense to me. _If_ there is any relation between the number of characters and the reaction time window (or the delay), then it should be an inverse one: More characters mean more reading time for the party members, and hence the message should be fired as close to the event as possible. (In case of spells mainly.) No?

But probably messages after damage spells would be rather annoying anyway, at least in boss fights ;)

Thanks so much!

**Comment by Nodd** [comment]
> Do you mean the delay or the reaction time window?

I meant the delay before the thought bubble expires. I tried to be smart but my reasoning was flawed, just forget it 😄 

> But probably messages after damage spells would be rather annoying anyway, at least in boss fights ;)

With a low probability, a CD between messages and lots of different sentences (even with very little differences) I think it can be quite fun, but it depends on the mindset in boss fight I guess. Disclaimer: I don't raid.

**Comment by tflo** [comment]
> I meant the delay before the thought bubble expires.

Ah, OK.

To avoid any misunderstanding: With “delay” in my OP I meant the time in-between the event and the Verbose action. As opposed to the “time window”, with which I meant the time duration available to hit the Message key, in case of bubble messages. (Probably the same as the duration of the bubble.)

When using emotes, a time window is irrelevant, but not the delay. When using bubble messages, the delay is (rather) irrelevant, since it is determined by when I hit the message key within the time window.
